GENERATED=\
	data.java \
	example.c \
	example.cs \
	example.encoded \
	example.h \
	example.javaencoded \
	example.py \
	example_encoder \
	log_message.java

all:

test:
	./run

clean:
	rm -f $(GENERATED) *.class

distclean: clean
