#!/bin/sh

# Auto generate code from .lc file
java -jar ../../compiler/labComm.jar \
  --c=example.c --h=example.h \
  --java=. \
  --cs=example.cs \
  --python=example.py \
  example.lc

# Compile executables
gcc -o example_encoder -I ../../lib/c/ \
	example_encoder.c \
 	example.c \
	../../lib/c/labcomm.c \
	../../lib/c//labcomm_fd_reader_writer.c
javac -cp ../../lib/java:. *.java

# Run through all executables (c->java->Python)
./example_encoder one two
java -cp ../../lib/java:. example_decoder_encoder example.encoded example.javaencoded
PYTHONPATH=../../lib/python ./example_decoder.py example.javaencoded
