#!/bin/sh

# Auto generate code from .lc file
java -jar ../../compiler/labcomm2014_compiler.jar \
  --c=example.c --h=example.h \
  --java=. \
  --cs=example.cs \
  --python=example.py \
  example.lc || exit 1

# Compile executables
(cd ../../lib/c; make all || exit 1)

gcc -Wall -Werror -o example_encoder -I../../lib/c/2014 \
    example_encoder.c \
    example.c \
    ../../lib/c/liblabcomm2014.a || exit 1

javac -cp ../../lib/java:. *.java || exit 1

# Run through all executables (c->java->Python)
./example_encoder one two || exit 1
java -cp ../../lib/java:. example_decoder_encoder example.encoded example.javaencoded || exit 1
PYTHONPATH=../../lib/python ./example_decoder.py example.javaencoded || exit 1
